title: "{{ site.company_name }}"
description: "{{ site.app_name }} — color-first communication for everyday life and business."

# Global variables
company_name: "LessWord UG"
app_name: "Color.cee"
url: "https://showcase.normanholz.de" # Your custom domain
baseurl: "" # Empty for custom domain
timezone: "Europe/Berlin"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Store Badges
ios_app_id: "1234567890"         # your Apple App ID (numeric)
android_package: "com.example.app" # your Play package name
badge_locale: "en-US"             # Apple badge locale (e.g., de-DE, en-US)
google_badge_locale: "en"         # Google badge locale code (e.g., de, en)
#apple_affiliate_token: ""         # optional: Apple affiliate ?at= token
#utm_campaign: "website-badge"     # optional: for Play referrer UTM

# SCSS Configuration
sass:
  sass_dir: assets/scss

# Exclude files from processing
exclude:
  - CLAUDE.md
# Toggles
analytics: false # Set true to enable GA snippet in _includes/analytics.html
formspree_endpoint: "https://formspree.io/f/xeozwpwr" # e.g., "https://formspree.io/f/xxxxxx"
# Navigation
nav:
  - title: Home
    url: /
  - title: App
    url: /app/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
